Personal/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('nmovie/', include('nmovie.urls')),
]

Personal/nmovie/urls.py
from django.urls import path
from . import views

app_name = 'nmovie'

urlpatterns = [
    path('index/', views.index, name="index"),
    path('receive/' , views.receiveAndSearch, name='receive'),
    path('search/', views.selected, name='selected'),
    path('research/', views.research, name='collect'),
    path('kakao/', views.send_kakao, name='kakao'),
]

Personal/nmovie/models.py
from django.db import models

# Create your models here.

Personal/nmovie/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import NaverMovie as nm
from . import NaverMovieNeo as neo
from . import predict as pre
from . import kakaoMessage as kakao

# Create your views here.
mnane = None
entire_var = None
movie_list = None
selected_mid = None
mmsg = None
title = None
link = None

def index(request):
    return render(request, 'nmovie/index.html')

def receiveAndSearch(request):
    global movie_list, mname
    query = request.GET['moviename']
    mname = query
    if query == '' or query == None: 
        context = {'error_msg':'검색어를 입력해주세요.'}
        return render(request, 'nmovie/error.html', context)
    print('query : ', query)
    html, soup = nm.getConnection(query=query)
    lists = nm.get_search_list(soup, *nm.find_more_list(soup))
    movie_list = lists
    print(list(movie_list['title']))
    render_list = list(movie_list['title'])
   
    context = {'movie_list':render_list}
    return render(request, 'nmovie/select.html', context)
    
def selected(request):
    global selected_mid, title, link
    sel = request.GET['select']
    if sel.isdecimal() == False: 
        context = {'error_msg':'숫자를 입력해주세요.'}
        return render(request, 'nmovie/error.html', context)
    sel = int(sel)
    target = movie_list.iloc[sel-1]
    print('target : ', target['title'], target['link'])
    title = target['title']
    link = target['link']
    selected_mid = neo.collect_comments1(target) # total, soup3, ratings
    if selected_mid[0] == 0:
        context = {'error_msg':'리뷰를 찾을 수 없습니다.'}
        return render(request, 'nmovie/error.html', context)
    context = {'total':selected_mid[0]}
    return render(request, 'nmovie/want_number.html', context)

def research(request):
    global mmsg
    nums = request.GET['nums']
    if nums.isdecimal() == False: 
        context = {'error_msg':'숫자를 입력해주세요.'}
        return render(request, 'nmovie/error.html', context)
    nums = int(nums)
    moveTo = int(nums / 10)
    msg1 = '요청하신 %d건을 수집하기 위해 총 %d 페이지를 탐색합니다.' % (nums, moveTo)
    msg2 = '분석이 끝날 때까지 잠시만 기다려주세요......'
    ratingStar, result_data = neo.collect_comments2(nums, moveTo, selected_mid[1], selected_mid[2])
    
    posCount, posPercent, ratingStar, msg_90 = pre.entire_predict(ratingStar, result_data)
    mmsg = title + '\n\n' + msg_90
    contextFinal = {'posCount':posCount, 'posPercent':posPercent, 'ratingStar':ratingStar}
    return render(request, 'nmovie/result.html', contextFinal)

def send_kakao(request):
    resCode = kakao.execute_msg(mmsg, link)
    if resCode == 200: return render(request, 'nmovie/complete.html')
    else: 
        context = {'error_msg':'전송에 실패했습니다.....'}
        return render(request, 'nmovie/error.html', context)

Personal/templates/nmovie/complete.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
    <title>HOME</title>
    <script>
        function goHome() {
            location.href = "{% url 'nmovie:index' %}";
        }
    </script>
</head>
<body>
    <div class="navbar navbar-expand navbar-dark bg-dark">
        <div class="container">
            <div class="navbar-header">
                <h1><a href="{% url 'nmovie:index' %}" class="navbar-brand">HOME</a></h1>
            </div>
        </div>
    </div>
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">완료!!</h1>
        </div>
    </div>
    <div class="container">
        <div class="container">
            <h2 style="color:blue;">전송이 완료되었습니다.</h2>   
        </div>
        <br><br><br><br>
        <div class="container">
            <button class="btn btn-secondary" onclick="goHome()">홈으로 돌아가기</button>
        </div>
    </div>
</body>
</html>

Personal/templates/nmovie/error.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
    <title>HOME</title>
    <script>
        function goHome() {
            location.href = "{% url 'nmovie:index' %}";
        }
    </script>
</head>
<body>
    <div class="navbar navbar-expand navbar-dark bg-dark">
        <div class="container">
            <div class="navbar-header">
                <h1><a href="{% url 'nmovie:index' %}" class="navbar-brand">HOME</a></h1>
            </div>
        </div>
    </div>
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">오류가 발생했습니다.....</h1>
        </div>
    </div>
    <div class="container">
        <div class="container">
            <h2 style="color:red;">{{error_msg}}</h2>   
        </div>
        <br><br><br><br>
        <div class="container">
            <button class="btn btn-secondary" onclick="goHome()">홈으로 돌아가기</button>
        </div>
    </div>
</body>
</html>

Personal/templates/nmovie/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
    <title>HOME</title>
</head>
<body>
    <div class="navbar navbar-expand navbar-dark bg-dark">
        <div class="container">
            <div class="navbar-header">
                <h1><a href="{% url 'nmovie:index' %}" class="navbar-brand">HOME</a></h1>
            </div>
        </div>
    </div>
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">이 영화, 어때요?</h1>
        </div>
    </div>
    <div class="container">
        <h3>원하시는 영화제목을 입력해주세요!</h3>
        <form class="form" action="{% url 'nmovie:receive' %}" method="get" encType="utf-8">
            <br><br><br><br>
            <div class="container">
                <div class="form-group row">
                    <label class="col-sm-2"><strong>영화 제목</strong></label>
                    <div class="col-sm-3">
                        <input type="text" name="moviename" class="form-control" />
                    </div>
                </div>
            </div>
            <br><br>
            <div class="container">
                <div class="form-group row">
                    <label class="col-sm-2"></label>
                    <div class="col-sm-3">
                        <input type="submit" class="btn btn-primary" value="검색" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</body>
</html>

Personal/templates/nmovie/result.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
    <title>HOME</title>
    <script>
        function goHome() {
            location.href = "{% url 'nmovie:index' %}";
        }
        function sendKakao() {
            location.href = "{% url 'nmovie:kakao' %}"
        }
    </script>
</head>
<body>
    <div class="navbar navbar-expand navbar-dark bg-dark">
        <div class="container">
            <div class="navbar-header">
                <h1><a href="{% url 'nmovie:index' %}" class="navbar-brand">HOME</a></h1>
            </div>
        </div>
    </div>
    <div class="jumbotron">
        <div class="container">
            {% if posPercent >= 0 and posPercent < 25 %}
                <h1 class="display-3">노잼!</h1>
            {% elif posPercent >= 25 and posPercent < 75 %}
                <h1 class="display-3">볼까? 말까?</h1>
            {% elif posPercent >= 75 and posPercent < 100 %}
                <h1 class="display-3">어머! 이건 꼭 사야 해!</h1>
            {% endif %}
        </div>
    </div>
    <div class="container">
        <div class="container">
            {% if posPercent >= 0 and posPercent < 25 %}
                <h2 class="display-3">으헝헝 노잼! 이걸 보느니 차라리 아무것도 안하고 말지...!!!!</h2>
            {% elif posPercent >= 25 and posPercent < 75 %}
                {% if 25 <= posPercent < 50 %}
                    <h2>관람객의 의견은  {% if posPercent >= 25 and posPercent < 35 %}대체로{% endif %} 부정적인 편입니다.....</h2>
                {% else %}
                    <h2>관람객의 의견은  {% if posPercent >= 65 and posPercent < 75 %}대체로{% endif %} 긍정적인 편입니다~</h2>
                {% endif %}
            {% elif posPercent >= 75 and posPercent < 100 %}
                <h2 class="display-3">꼭 보세요! 무조건 보세요!</h2>
            {% endif %}
            <br>
            {% if posPercent >= 0 and posPercent < 25 %}
                <img src="{% static 'img/jo.jpg' %}" />
            {% elif posPercent >= 25 and posPercent < 75 %}
                <img src="{% static 'img/gomin.png' %}" />
            {% elif posPercent >= 75 and posPercent < 100 %}
                <img src="{% static 'img/wow.jpg' %}" />
            {% endif %}
            <p><hr><p>
            <h4>긍정적인 의견 : {{posPercent}}%</h4>
            <br><br>
            <h5>이 영화를 시청한 사람들의 평점입니다.</h5>
            {% for star in ratingStar %}
                <h3>{{star}}</h3>
            {% endfor %}
            <br><br>
            <p><hr><p>
            <br><br>
            <h5>관람객들의 리뷰에 가장 많이 등장한 단어들입니다.</h5>
            <img src="{% static 'img/result_wordcloud.jpg' %}" />
            <br><br>
            <p><hr><p>
            <br><br>
            <button class="btn btn-secondary" onclick="goHome()">홈으로 돌아가기</button>
            <button class="btn btn-warning" onclick="sendKakao()">카카오톡 전송</button>
        </div>
    </div>
</body>
</html>

Personal/templates/nmovie/select.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
    <title>HOME</title>
    <style>
        .solid{width:620px; height:500px; overflow:scroll; border:5px solid gray; padding:5px 5px 5px 5px;}
    </style>
</head>
<body>
    <div class="navbar navbar-expand navbar-dark bg-dark">
        <div class="container">
            <div class="navbar-header">
                <h1><a href="{% url 'nmovie:index' %}" class="navbar-brand">HOME</a></h1>
            </div>
        </div>
    </div>
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">검색 결과</h1>
        </div>
    </div>

    <div class="container">
        <div class="container">
            <div class="solid">
                {% for movie in movie_list %}
                    <h5>{{forloop.counter}}.&nbsp;{{movie}}</h5><br>
                {% endfor %}
            </div>
        </div>
        <div class="container">
            <br>
            <h4>원하시는 번호를 입력해주세요.</h4>
        </div>
        <br><br><br><br>
        <div class="container">
            <form class="form" action="{% url 'nmovie:selected' %}" method="get" enctype="utf-8">
                <div class="form-group row">
                    <label class="col-sm-2"><strong>번호</strong></label>
                    <div class="col-sm-3">
                        <input type="text" name="select" class="form-control" />
                    </div>
                </div>
                <br><br>
                <div class="form-group row">
                    <label class="col-sm-2"></label>
                    <div class="col-sm-3">
                        <input type="submit" value="선택" class="btn btn-primary" />
                    </div>
                </div>
            </form>
        </div>
            
    </div>
</body>
</html>

Personal/templates/nmovie/want_number.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
    <title>Choice numbers!</title>
</head>
<body>
    <div class="navbar navbar-expand navbar-dark bg-dark">
        <div class="container">
            <div class="navbar-header">
                <h1><a href="{% url 'nmovie:index' %}" class="navbar-brand">HOME</a></h1>
            </div>
        </div>
    </div>
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">Choice numbers!</h1>
        </div>
    </div>
    <div class="container">
        <h3>총 {{total}}건의 리뷰를 찾았습니다.</h3><br>
        <h4>몇 건의 리뷰를 수집하시겠습니까? (더 많은 리뷰를 수집하실수록 예측 정확도가 향상됩니다.)</h4>
        <br><br>
        <form class="form" action="{% url 'nmovie:collect' %}" method="get" encType="utf-8">
            <div class="container">
                <div class="form-group row">
                    <label class="col-sm-2"><strong>수집 갯수</strong></label>
                    <div class="col-sm-3">
                        <input type="text" name="nums" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="form-group row">
                    <label class="col-sm-2"></label>
                    <div class="col-sm-3">
                        <input type="submit" class="btn btn-primary" value="검색" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</body>
</html>